# Generated by Django 4.2.1 on 2023-06-03 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone_no_1', models.BigIntegerField()),
                ('phone_no_2', models.BigIntegerField()),
                ('reg_date', models.DateTimeField()),
                ('mail', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('available', models.BooleanField()),
                ('inventory', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock_card',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('order', models.IntegerField()),
                ('amount', models.FloatField()),
                ('advance', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField()),
                ('outstanding', models.FloatField(null=True)),
                ('total_p', models.FloatField(null=True)),
                ('means_of_Pay', models.CharField(max_length=100)),
                ('c_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockcard.customers')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockcard.items')),
            ],
        ),
    ]
