# Generated by Django 4.2.1 on 2023-06-03 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='country',
            new_name='address',
        ),
    ]
