# Generated by Django 4.2.1 on 2023-06-03 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcard', '0002_rename_country_customers_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_card',
            name='item',
            field=models.CharField(max_length=100),
        ),
    ]
