# Generated by Django 4.2.1 on 2023-06-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockcard', '0003_alter_stock_card_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_card',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stockcard.items'),
        ),
    ]
