# Generated by Django 4.2.1 on 2023-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockcard', '0005_c_stat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='c_stat',
            old_name='Out',
            new_name='out',
        ),
    ]
