# Generated by Django 4.2.1 on 2023-06-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockcard', '0006_rename_out_c_stat_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c_stat',
            name='advance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='c_stat',
            name='out',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='c_stat',
            name='paid',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
